name: Publish Package to npmjs
# change branch name to re-enable pipeline

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm ci
        run: |
          npm ci

      - name: Build esm package
        run: |
          npm run rollup

      - name: version
        outputs:
          version: ${{ steps.version_step.outputs.version }}
        run: echo "version=$(./bin/azblogfilter --version)" >> "$GITHUB_OUTPUT"
        id: version_step

      - name: release
        uses: actions/create-release@v1
        id: create_release
        needs: version
        with:
          draft: false
          prerelease: false
          release_name: ${{ needs.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Sentry Release
        uses: getsentry/action-release@v1.4.1
        needs: version
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
        with:
          environment: production
          sourcemaps: './dist/esm/'
          ignore_missing: true
          ignore_empty: true
          version: ${{ needs.version.outputs.version }}

      - name: Deploy to cdn (version)
        uses: Creepios/sftp-action@v1.0.3
        needs: version
        with:
          host: ${{ secrets.FTP_SERVER_URL }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: "dist"
          remotePath: "hermine-chat/versions/${{ needs.version.outputs.version }}/"

      - name: Deploy to cdn (current)
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER_URL }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: "dist"
          remotePath: "hermine-chat/current/"

      - name: Deploy to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

